# Generated by Django 4.2.5 on 2023-09-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number_of_people', models.PositiveIntegerField(default=0)),
                ('number_of_seats', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('number_of_people', models.PositiveIntegerField(default=0)),
                ('number_of_seats', models.PositiveIntegerField(default=0)),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bustype')),
            ],
        ),
    ]
