# Generated by Django 4.2.5 on 2023-09-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bus_number_of_special_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='bustype',
            name='number_of_seats',
        ),
    ]
